/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ApplicationSearchCriteria } from "./applicationsearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for Applications
 */
export class ApplicationSearchRequest extends SpeakeasyBase {
    /**
     * Search criteria for Applications
     */
    @SpeakeasyMetadata()
    @Expose({ name: "search" })
    @Type(() => ApplicationSearchCriteria)
    search?: ApplicationSearchCriteria;
}
