/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Used to indicate what type of attestation was included in the authenticator response for a given WebAuthn credential at the time it was created
 */
export enum AttestationType {
  Basic = "basic",
  Self = "self",
  AttestationCa = "attestationCa",
  AnonymizationCa = "anonymizationCa",
  None = "none",
}
