/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AuditLog } from "./auditlog";
import { Expose, Type } from "class-transformer";

/**
 * Audit log response.
 */
export class AuditLogResponse extends SpeakeasyBase {
  /**
   * An audit log.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "auditLog" })
  @Type(() => AuditLog)
  auditLog?: AuditLog;
}
