/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AuditLog } from "./auditlog";
import { EventInfo } from "./eventinfo";
import { Expose, Type } from "class-transformer";

export class AuditLogRequest extends SpeakeasyBase {
  /**
   * An audit log.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "auditLog" })
  @Type(() => AuditLog)
  auditLog?: AuditLog;

  /**
   * Information about a user event (login, register, etc) that helps identify the source of the event (location, device type, OS, etc).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "eventInfo" })
  @Type(() => EventInfo)
  eventInfo?: EventInfo;
}
