/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes the <a href="https:www.w3.orgTRwebauthn-2#authenticator-attachment-modality">authenticator attachment modality<a>.
 */
export enum AuthenticatorAttachment {
  Platform = "platform",
  CrossPlatform = "crossPlatform",
}
