/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum BreachedPasswordStatus {
  None = "None",
  ExactMatch = "ExactMatch",
  SubAddressMatch = "SubAddressMatch",
  PasswordOnly = "PasswordOnly",
  CommonPassword = "CommonPassword",
}
