/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum BreachActionEnum {
  Off = "Off",
  RecordOnly = "RecordOnly",
  NotifyUser = "NotifyUser",
  RequireChange = "RequireChange",
}
