/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * XML canonicalization method enumeration. This is used for the IdP and SP side of FusionAuth SAML.
 */
export enum CanonicalizationMethod {
  Exclusive = "exclusive",
  ExclusiveWithComments = "exclusive_with_comments",
  Inclusive = "inclusive",
  InclusiveWithComments = "inclusive_with_comments",
}
