/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum CaptchaMethodEnum {
  GoogleRecaptchaV2 = "GoogleRecaptchaV2",
  GoogleRecaptchaV3 = "GoogleRecaptchaV3",
  HCaptcha = "HCaptcha",
  HCaptchaEnterprise = "HCaptchaEnterprise",
}
