/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CertificateInformation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "issuer" })
    issuer?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "md5Fingerprint" })
    md5Fingerprint?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "serialNumber" })
    serialNumber?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sha1Fingerprint" })
    sha1Fingerprint?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sha1Thumbprint" })
    sha1Thumbprint?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sha256Fingerprint" })
    sha256Fingerprint?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sha256Thumbprint" })
    sha256Thumbprint?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "subject" })
    subject?: string;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "validFrom" })
    validFrom?: number;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "validTo" })
    validTo?: number;
}
