/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ClientAuthenticationMethod {
    None = "none",
    ClientSecretBasic = "client_secret_basic",
    ClientSecretPost = "client_secret_post",
}
