/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ClientAuthenticationPolicyEnum {
  Required = "Required",
  NotRequired = "NotRequired",
  NotRequiredWhenUsingPKCE = "NotRequiredWhenUsingPKCE",
}
