/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BaseConnectorConfiguration } from "./baseconnectorconfiguration";
import { Expose, Type } from "class-transformer";

export class ConnectorRequest extends SpeakeasyBase {
    /**
     * Do not require a setter for 'type', it is defined by the concrete class and is not mutable
     */
    @SpeakeasyMetadata()
    @Expose({ name: "connector" })
    @Type(() => BaseConnectorConfiguration)
    connector?: BaseConnectorConfiguration;
}
