/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class ConnectorPolicyData extends SpeakeasyBase {}

export class ConnectorPolicy extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connectorId" })
    connectorId?: string;

    @SpeakeasyMetadata({ elemType: ConnectorPolicyData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, ConnectorPolicyData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], ConnectorPolicyData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, ConnectorPolicyData>;

    @SpeakeasyMetadata()
    @Expose({ name: "domains" })
    domains?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "migrate" })
    migrate?: boolean;
}
