/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConsentSearchCriteria } from "./consentsearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for Consents
 */
export class ConsentSearchRequest extends SpeakeasyBase {
    /**
     * Search criteria for Consents
     */
    @SpeakeasyMetadata()
    @Expose({ name: "search" })
    @Type(() => ConsentSearchCriteria)
    search?: ConsentSearchCriteria;
}
