/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Status for content like usernames, profile attributes, etc.
 */
export enum ContentStatus {
    Active = "ACTIVE",
    Pending = "PENDING",
    Rejected = "REJECTED",
}
