/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Status for content like usernames, profile attributes, etc.
 */
export enum ContentStatusEnum {
  Active = "ACTIVE",
  Pending = "PENDING",
  Rejected = "REJECTED",
}
