/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * A number identifying a cryptographic algorithm. Values should be registered with the <a  href="https:www.iana.orgassignmentscosecose.xhtml#algorithms">IANA COSE Algorithms registry<a>
 */
export enum CoseAlgorithmIdentifier {
  Es256 = "ES256",
  Es384 = "ES384",
  Es512 = "ES512",
  Rs256 = "RS256",
  Rs384 = "RS384",
  Rs512 = "RS512",
  Ps256 = "PS256",
  Ps384 = "PS384",
  Ps512 = "PS512",
}
