/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum DeviceType {
  Browser = "BROWSER",
  Desktop = "DESKTOP",
  Laptop = "LAPTOP",
  Mobile = "MOBILE",
  Other = "OTHER",
  Server = "SERVER",
  Tablet = "TABLET",
  Tv = "TV",
  Unknown = "UNKNOWN",
}
