/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EntityGrantSearchCriteria } from "./entitygrantsearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for entity grants.
 */
export class EntityGrantSearchRequest extends SpeakeasyBase {
    /**
     * Search criteria for entity grants.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "search" })
    @Type(() => EntityGrantSearchCriteria)
    search?: EntityGrantSearchCriteria;
}
