/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EntityTypeSearchCriteria } from "./entitytypesearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for entity types.
 */
export class EntityTypeSearchRequest extends SpeakeasyBase {
    /**
     * Search criteria for entity types.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "search" })
    @Type(() => EntityTypeSearchCriteria)
    search?: EntityTypeSearchCriteria;
}
