/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * JWT Configuration for entities.
 */
export class EntityJWTConfiguration extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "accessTokenKeyId" })
    accessTokenKeyId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "timeToLiveInSeconds" })
    timeToLiveInSeconds?: number;
}
