/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Entity } from "./entity";
import { Expose, Type } from "class-transformer";

/**
 * Search request for entities
 */
export class EntitySearchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Entity })
  @Expose({ name: "entities" })
  @Type(() => Entity)
  entities?: Entity[];

  @SpeakeasyMetadata()
  @Expose({ name: "total" })
  total?: number;
}
