/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EntityGrant } from "./entitygrant";
import { Expose, Type } from "class-transformer";

/**
 * Entity grant API request object.
 */
export class EntityGrantRequest extends SpeakeasyBase {
  /**
   * A grant for an entity to a user or another entity.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "grant" })
  @Type(() => EntityGrant)
  grant?: EntityGrant;
}
