/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EntityGrant } from "./entitygrant";
import { Expose, Type } from "class-transformer";

/**
 * Search request for entity grants.
 */
export class EntityGrantSearchResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: EntityGrant })
    @Expose({ name: "grants" })
    @Type(() => EntityGrant)
    grants?: EntityGrant[];

    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total?: number;
}
