/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Event Log Type
 */
export enum EventLogType {
    Information = "Information",
    Debug = "Debug",
    Error = "Error",
}
