/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EventLog } from "./eventlog";
import { Expose, Type } from "class-transformer";

/**
 * Event log response.
 */
export class EventLogResponse extends SpeakeasyBase {
    /**
     * Event log used internally by FusionAuth to help developers debug hooks, Webhooks, email templates, etc.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "eventLog" })
    @Type(() => EventLog)
    eventLog?: EventLog;
}
