/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ExpiryUnit {
    Minutes = "MINUTES",
    Hours = "HOURS",
    Days = "DAYS",
    Weeks = "WEEKS",
    Months = "MONTHS",
    Years = "YEARS",
}
