/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * API request for sending out family requests to parent's.
 */
export class FamilyEmailRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "parentEmail" })
    parentEmail?: string;
}
