/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FamilyRoleEnum } from "./familyroleenum";
import { Expose } from "class-transformer";

/**
 * Models a single family member.
 */
export class FamilyMember extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  data?: Record<string, Record<string, any>>;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "insertInstant" })
  insertInstant?: number;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "lastUpdateInstant" })
  lastUpdateInstant?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "owner" })
  owner?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "role" })
  role?: FamilyRoleEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "userId" })
  userId?: string;
}
