/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Form } from "./form";
import { Expose, Type } from "class-transformer";

/**
 * Form response.
 */
export class FormResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "form" })
    @Type(() => Form)
    form?: Form;

    @SpeakeasyMetadata({ elemType: Form })
    @Expose({ name: "forms" })
    @Type(() => Form)
    forms?: Form[];
}
