/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum FormDataTypeEnum {
  Bool = "bool",
  Consent = "consent",
  Date = "date",
  Email = "email",
  Number = "number",
  String = "string",
}
