/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum FormType {
  Registration = "registration",
  AdminRegistration = "adminRegistration",
  AdminUser = "adminUser",
  SelfServiceUser = "selfServiceUser",
}
