/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Group } from "./group";
import { Expose, Type } from "class-transformer";

/**
 * Group API request object.
 */
export class GroupRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "group" })
  @Type(() => Group)
  group?: Group;

  @SpeakeasyMetadata()
  @Expose({ name: "roleIds" })
  roleIds?: string[];
}
