/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Group } from "./group";
import { Expose, Type } from "class-transformer";

/**
 * Group API response object.
 */
export class GroupResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "group" })
  @Type(() => Group)
  group?: Group;

  @SpeakeasyMetadata({ elemType: Group })
  @Expose({ name: "groups" })
  @Type(() => Group)
  groups?: Group[];
}
