/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Group } from "./group";
import { Expose, Type } from "class-transformer";

/**
 * Search response for Groups
 */
export class GroupSearchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Group })
  @Expose({ name: "groups" })
  @Type(() => Group)
  groups?: Group[];

  @SpeakeasyMetadata()
  @Expose({ name: "total" })
  total?: number;
}
