/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum HTTPMethod {
    Get = "GET",
    Post = "POST",
    Put = "PUT",
    Delete = "DELETE",
    Head = "HEAD",
    Options = "OPTIONS",
    Patch = "PATCH",
}
