/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class IdentityProviderLinkData extends SpeakeasyBase {}

export class IdentityProviderLink extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: IdentityProviderLinkData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, IdentityProviderLinkData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], IdentityProviderLinkData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, IdentityProviderLinkData>;

    @SpeakeasyMetadata()
    @Expose({ name: "displayName" })
    displayName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "identityProviderId" })
    identityProviderId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "identityProviderUserId" })
    identityProviderUserId?: string;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insertInstant" })
    insertInstant?: number;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastLoginInstant" })
    lastLoginInstant?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "tenantId" })
    tenantId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId?: string;
}
