/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum IdentityProviderLoginMethodEnum {
  UsePopup = "UsePopup",
  UseRedirect = "UseRedirect",
  UseVendorJavaScript = "UseVendorJavaScript",
}
