/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MetaData } from "./metadata";
import { Expose, Transform, Type } from "class-transformer";

export class IdentityProviderStartLoginRequestState extends SpeakeasyBase {}

export class IdentityProviderStartLoginRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "applicationId" })
    applicationId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    data?: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "identityProviderId" })
    identityProviderId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ipAddress" })
    ipAddress?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "loginId" })
    loginId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metaData" })
    @Type(() => MetaData)
    metaData?: MetaData;

    @SpeakeasyMetadata()
    @Expose({ name: "newDevice" })
    newDevice?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "noJWT" })
    noJWT?: boolean;

    @SpeakeasyMetadata({ elemType: IdentityProviderStartLoginRequestState })
    @Expose({ name: "state" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, IdentityProviderStartLoginRequestState> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], IdentityProviderStartLoginRequestState);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    state?: Record<string, IdentityProviderStartLoginRequestState>;
}
