/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The IdP behavior when no user link has been made yet.
 */
export enum IdentityProviderLinkingStrategy {
  CreatePendingLink = "CreatePendingLink",
  Disabled = "Disabled",
  LinkAnonymously = "LinkAnonymously",
  LinkByEmail = "LinkByEmail",
  LinkByEmailForExistingUser = "LinkByEmailForExistingUser",
  LinkByUsername = "LinkByUsername",
  LinkByUsernameForExistingUser = "LinkByUsernameForExistingUser",
  Unsupported = "Unsupported",
}
