/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IdentityProviderSearchCriteria } from "./identityprovidersearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for Identity Providers
 */
export class IdentityProviderSearchRequest extends SpeakeasyBase {
  /**
   * Search criteria for Identity Providers.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "search" })
  @Type(() => IdentityProviderSearchCriteria)
  search?: IdentityProviderSearchCriteria;
}
