/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum IdentityProviderType {
  Apple = "Apple",
  EpicGames = "EpicGames",
  ExternalJWT = "ExternalJWT",
  Facebook = "Facebook",
  Google = "Google",
  Hypr = "HYPR",
  LinkedIn = "LinkedIn",
  Nintendo = "Nintendo",
  OpenIDConnect = "OpenIDConnect",
  SAMLv2 = "SAMLv2",
  SAMLv2IdPInitiated = "SAMLv2IdPInitiated",
  SonyPSN = "SonyPSN",
  Steam = "Steam",
  Twitch = "Twitch",
  Twitter = "Twitter",
  Xbox = "Xbox",
}
