/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Integrations } from "./integrations";
import { Expose, Type } from "class-transformer";

/**
 * The Integration Response
 */
export class IntegrationResponse extends SpeakeasyBase {
    /**
     * Available Integrations
     */
    @SpeakeasyMetadata()
    @Expose({ name: "integrations" })
    @Type(() => Integrations)
    integrations?: Integrations;
}
