/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IPAccessControlEntry } from "./ipaccesscontrolentry";
import { Expose, Transform, Type } from "class-transformer";

export class IPAccessControlListData extends SpeakeasyBase {}

export class IPAccessControlList extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: IPAccessControlListData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, IPAccessControlListData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], IPAccessControlListData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, IPAccessControlListData>;

    @SpeakeasyMetadata({ elemType: IPAccessControlEntry })
    @Expose({ name: "entries" })
    @Type(() => IPAccessControlEntry)
    entries?: IPAccessControlEntry[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insertInstant" })
    insertInstant?: number;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastUpdateInstant" })
    lastUpdateInstant?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
