/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class JWTVendRequestClaims extends SpeakeasyBase {}

export class JWTVendRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: JWTVendRequestClaims })
    @Expose({ name: "claims" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, JWTVendRequestClaims> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], JWTVendRequestClaims);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    claims?: Record<string, JWTVendRequestClaims>;

    @SpeakeasyMetadata()
    @Expose({ name: "keyId" })
    keyId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "timeToLiveInSeconds" })
    timeToLiveInSeconds?: number;
}
