/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum KeyAlgorithmEnum {
  Es256 = "ES256",
  Es384 = "ES384",
  Es512 = "ES512",
  Hs256 = "HS256",
  Hs384 = "HS384",
  Hs512 = "HS512",
  Rs256 = "RS256",
  Rs384 = "RS384",
  Rs512 = "RS512",
}
