/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Key } from "./key";
import { Expose, Type } from "class-transformer";

/**
 * Key API request object.
 */
export class KeyRequest extends SpeakeasyBase {
    /**
     * Domain for a public key, key pair or an HMAC secret. This is used by KeyMaster to manage keys for JWTs, SAML, etc.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    @Type(() => Key)
    key?: Key;
}
