/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Key } from "./key";
import { Expose, Type } from "class-transformer";

/**
 * Key API response object.
 */
export class KeyResponse extends SpeakeasyBase {
  /**
   * Domain for a public key, key pair or an HMAC secret. This is used by KeyMaster to manage keys for JWTs, SAML, etc.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "key" })
  @Type(() => Key)
  key?: Key;

  @SpeakeasyMetadata({ elemType: Key })
  @Expose({ name: "keys" })
  @Type(() => Key)
  keys?: Key[];
}
