/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Key } from "./key";
import { Expose, Type } from "class-transformer";

/**
 * Key search response
 */
export class KeySearchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Key })
  @Expose({ name: "keys" })
  @Type(() => Key)
  keys?: Key[];

  @SpeakeasyMetadata()
  @Expose({ name: "total" })
  total?: number;
}
