/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Lambda } from "./lambda";
import { Expose, Type } from "class-transformer";

/**
 * Lambda search response
 */
export class LambdaSearchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Lambda })
  @Expose({ name: "lambdas" })
  @Type(() => Lambda)
  lambdas?: Lambda[];

  @SpeakeasyMetadata()
  @Expose({ name: "total" })
  total?: number;
}
