/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LambdaEngineType } from "./lambdaenginetype";
import { LambdaType } from "./lambdatype";
import { Expose } from "class-transformer";

/**
 * A JavaScript lambda function that is executed during certain events inside FusionAuth.
 */
export class Lambda extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "body" })
  body?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "debug" })
  debug?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "engineType" })
  engineType?: LambdaEngineType;

  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "insertInstant" })
  insertInstant?: number;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "lastUpdateInstant" })
  lastUpdateInstant?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The types of lambdas that indicate how they are invoked by FusionAuth.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: LambdaType;
}
