/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LambdaSearchCriteria } from "./lambdasearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for Lambdas
 */
export class LambdaSearchRequest extends SpeakeasyBase {
    /**
     * Search criteria for Lambdas
     */
    @SpeakeasyMetadata()
    @Expose({ name: "search" })
    @Type(() => LambdaSearchCriteria)
    search?: LambdaSearchCriteria;
}
