/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DeleteConfiguration } from "./deleteconfiguration";
import { Expose, Type } from "class-transformer";

export class LoginRecordConfiguration extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "delete" })
  @Type(() => DeleteConfiguration)
  delete?: DeleteConfiguration;
}
