/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MetaData } from "./metadata";
import { Expose, Type } from "class-transformer";

/**
 * Login API request object.
 */
export class LoginRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "applicationId" })
  applicationId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "ipAddress" })
  ipAddress?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "loginId" })
  loginId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "metaData" })
  @Type(() => MetaData)
  metaData?: MetaData;

  @SpeakeasyMetadata()
  @Expose({ name: "newDevice" })
  newDevice?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "noJWT" })
  noJWT?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "oneTimePassword" })
  oneTimePassword?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "password" })
  password?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "twoFactorTrustId" })
  twoFactorTrustId?: string;
}
