/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LoginRecordSearchCriteria } from "./loginrecordsearchcriteria";
import { Expose, Type } from "class-transformer";

export class LoginRecordSearchRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "retrieveTotal" })
    retrieveTotal?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "search" })
    @Type(() => LoginRecordSearchCriteria)
    search?: LoginRecordSearchCriteria;
}
