/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class LoginConfiguration extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "allowTokenRefresh" })
    allowTokenRefresh?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "generateRefreshTokens" })
    generateRefreshTokens?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "requireAuthentication" })
    requireAuthentication?: boolean;
}
