/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GroupMember } from "./groupmember";
import { Expose, Type } from "class-transformer";

/**
 * Group Member Response
 */
export class MemberResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: GroupMember })
  @Expose({ name: "members" })
  @Type(() => GroupMember)
  members?: GroupMember[];
}
