/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BaseMessengerConfiguration } from "./basemessengerconfiguration";
import { Expose, Type } from "class-transformer";

export class MessengerRequest extends SpeakeasyBase {
    /**
     * Do not require a setter for 'type', it is defined by the concrete class and is not mutable
     */
    @SpeakeasyMetadata()
    @Expose({ name: "messenger" })
    @Type(() => BaseMessengerConfiguration)
    messenger?: BaseMessengerConfiguration;
}
