/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MessageTemplate } from "./messagetemplate";
import { Expose, Type } from "class-transformer";

/**
 * A Message Template Request to the API
 */
export class MessageTemplateRequest extends SpeakeasyBase {
    /**
     * Stores an message template used to distribute messages;
     */
    @SpeakeasyMetadata()
    @Expose({ name: "messageTemplate" })
    @Type(() => MessageTemplate)
    messageTemplate?: MessageTemplate;
}
