/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MessageType } from "./messagetype";
import { Expose, Transform } from "class-transformer";

export class MessageTemplateData extends SpeakeasyBase {}

/**
 * Stores an message template used to distribute messages;
 */
export class MessageTemplate extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: MessageTemplateData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, MessageTemplateData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], MessageTemplateData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, MessageTemplateData>;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insertInstant" })
    insertInstant?: number;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastUpdateInstant" })
    lastUpdateInstant?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: MessageType;
}
