/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DeviceInfo } from "./deviceinfo";
import { Expose, Transform, Type } from "class-transformer";

export class MetaDataData extends SpeakeasyBase {}

export class MetaData extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: MetaDataData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, MetaDataData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], MetaDataData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, MetaDataData>;

    @SpeakeasyMetadata()
    @Expose({ name: "device" })
    @Type(() => DeviceInfo)
    device?: DeviceInfo;

    @SpeakeasyMetadata()
    @Expose({ name: "scopes" })
    scopes?: any[];
}
