/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TOTPAlgorithm } from "./totpalgorithm";
import { Expose } from "class-transformer";

export class MultiFactorAuthenticatorMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "algorithm" })
    algorithm?: TOTPAlgorithm;

    @SpeakeasyMetadata()
    @Expose({ name: "codeLength" })
    codeLength?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "timeStep" })
    timeStep?: number;
}
