/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OAuthErrorReason } from "./oautherrorreason";
import { OAuthErrorType } from "./oautherrortype";
import { TwoFactorMethod } from "./twofactormethod";
import { Expose, Type } from "class-transformer";

export class OAuthError extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "change_password_id" })
    changePasswordId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error?: OAuthErrorType;

    @SpeakeasyMetadata()
    @Expose({ name: "error_description" })
    errorDescription?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "error_reason" })
    errorReason?: OAuthErrorReason;

    @SpeakeasyMetadata()
    @Expose({ name: "error_uri" })
    errorUri?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "two_factor_id" })
    twoFactorId?: string;

    @SpeakeasyMetadata({ elemType: TwoFactorMethod })
    @Expose({ name: "two_factor_methods" })
    @Type(() => TwoFactorMethod)
    twoFactorMethods?: TwoFactorMethod[];
}
