/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum Oauth2AuthorizedURLValidationPolicyEnum {
  AllowWildcards = "AllowWildcards",
  ExactMatch = "ExactMatch",
}
