/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IdentityProviderLinkingStrategy } from "./identityproviderlinkingstrategy";
import { IdentityProviderOauth2Configuration } from "./identityprovideroauth2configuration";
import { IdentityProviderTenantConfiguration } from "./identityprovidertenantconfiguration";
import { IdentityProviderType } from "./identityprovidertype";
import { OpenIdConnectApplicationConfiguration } from "./openidconnectapplicationconfiguration";
import { ProviderLambdaConfiguration } from "./providerlambdaconfiguration";
import { Expose, Transform, Type } from "class-transformer";

export class OpenIdConnectIdentityProviderData extends SpeakeasyBase {}

export class OpenIdConnectIdentityProvider extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: OpenIdConnectApplicationConfiguration })
    @Expose({ name: "applicationConfiguration" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, OpenIdConnectApplicationConfiguration> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], OpenIdConnectApplicationConfiguration);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    applicationConfiguration?: Record<string, OpenIdConnectApplicationConfiguration>;

    @SpeakeasyMetadata()
    @Expose({ name: "buttonImageURL" })
    buttonImageURL?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "buttonText" })
    buttonText?: string;

    @SpeakeasyMetadata({ elemType: OpenIdConnectIdentityProviderData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, OpenIdConnectIdentityProviderData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], OpenIdConnectIdentityProviderData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, OpenIdConnectIdentityProviderData>;

    @SpeakeasyMetadata()
    @Expose({ name: "debug" })
    debug?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "domains" })
    domains?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insertInstant" })
    insertInstant?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "lambdaConfiguration" })
    @Type(() => ProviderLambdaConfiguration)
    lambdaConfiguration?: ProviderLambdaConfiguration;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastUpdateInstant" })
    lastUpdateInstant?: number;

    /**
     * The IdP behavior when no user link has been made yet.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linkingStrategy" })
    linkingStrategy?: IdentityProviderLinkingStrategy;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "oauth2" })
    @Type(() => IdentityProviderOauth2Configuration)
    oauth2?: IdentityProviderOauth2Configuration;

    @SpeakeasyMetadata()
    @Expose({ name: "postRequest" })
    postRequest?: boolean;

    @SpeakeasyMetadata({ elemType: IdentityProviderTenantConfiguration })
    @Expose({ name: "tenantConfiguration" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, IdentityProviderTenantConfiguration> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], IdentityProviderTenantConfiguration);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    tenantConfiguration?: Record<string, IdentityProviderTenantConfiguration>;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: IdentityProviderType;
}
