/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BreachAction } from "./breachaction";
import { BreachMatchMode } from "./breachmatchmode";
import { Expose } from "class-transformer";

export class PasswordBreachDetection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "matchMode" })
    matchMode?: BreachMatchMode;

    @SpeakeasyMetadata()
    @Expose({ name: "notifyUserEmailTemplateId" })
    notifyUserEmailTemplateId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "onLogin" })
    onLogin?: BreachAction;
}
