/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PasswordValidationRules } from "./passwordvalidationrules";
import { Expose, Type } from "class-transformer";

export class PasswordValidationRulesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "passwordValidationRules" })
    @Type(() => PasswordValidationRules)
    passwordValidationRules?: PasswordValidationRules;
}
