/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class PasswordlessStartRequestState extends SpeakeasyBase {}

export class PasswordlessStartRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "applicationId" })
    applicationId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "loginId" })
    loginId?: string;

    @SpeakeasyMetadata({ elemType: PasswordlessStartRequestState })
    @Expose({ name: "state" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, PasswordlessStartRequestState> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], PasswordlessStartRequestState);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    state?: Record<string, PasswordlessStartRequestState>;
}
