/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Email } from "./email";
import { Errors } from "./errors";
import { Expose, Type } from "class-transformer";

export class PreviewResponse extends SpeakeasyBase {
    /**
     * This class is an abstraction of a simple email message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    @Type(() => Email)
    email?: Email;

    /**
     * Standard error domain object that can also be used as the response from an API call.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "errors" })
    @Type(() => Errors)
    errors?: Errors;
}
