/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MessageTemplate } from "./messagetemplate";
import { Expose, Type } from "class-transformer";

export class PreviewMessageTemplateRequest extends SpeakeasyBase {
  /**
   * A Locale object represents a specific geographical, political, or cultural region.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "locale" })
  locale?: string;

  /**
   * Stores an message template used to distribute messages;
   */
  @SpeakeasyMetadata()
  @Expose({ name: "messageTemplate" })
  @Type(() => MessageTemplate)
  messageTemplate?: MessageTemplate;
}
