/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PublicKeyCredentialType } from "./publickeycredentialtype";
import { Expose } from "class-transformer";

/**
 * Contains attributes for the Relying Party to refer to an existing public key credential as an input parameter.
 */
export class PublicKeyCredentialDescriptor extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "transports" })
  transports?: string[];

  /**
   * Defines valid credential types. This is an extension point in the WebAuthn spec. The only defined value at this time is "public-key"
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: PublicKeyCredentialType;
}
