/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Request for managing FusionAuth Reactor and licenses.
 */
export class ReactorRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "license" })
  license?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "licenseId" })
  licenseId?: string;
}
