/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Reindex API request
 */
export class ReindexRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "index" })
    index?: string;
}
