/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Describes the Relying Party's requirements for <a href="https:www.w3.orgTRwebauthn-2#client-side-discoverable-credential">client-side  discoverable credentials<a> (formerly known as "resident keys")
 */
export enum ResidentKeyRequirementEnum {
  Discouraged = "discouraged",
  Preferred = "preferred",
  Required = "required",
}
