/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum SAMLv2DestinationAssertionPolicyEnum {
  Enabled = "Enabled",
  Disabled = "Disabled",
  AllowAlternates = "AllowAlternates",
}
