/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum SAMLv2DestinationAssertionPolicy {
    Enabled = "Enabled",
    Disabled = "Disabled",
    AllowAlternates = "AllowAlternates",
}
