/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { User } from "./user";
import { Expose, Type } from "class-transformer";

/**
 * Search API response.
 */
export class SearchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "total" })
  total?: number;

  @SpeakeasyMetadata({ elemType: User })
  @Expose({ name: "users" })
  @Type(() => User)
  users?: User[];
}
