/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IdentityProviderLinkingStrategy } from "./identityproviderlinkingstrategy";
import { IdentityProviderTenantConfiguration } from "./identityprovidertenantconfiguration";
import { IdentityProviderType } from "./identityprovidertype";
import { ProviderLambdaConfiguration } from "./providerlambdaconfiguration";
import { SonyPSNApplicationConfiguration } from "./sonypsnapplicationconfiguration";
import { Expose, Transform, Type } from "class-transformer";

export class SonyPSNIdentityProviderData extends SpeakeasyBase {}

/**
 * SonyPSN gaming login provider.
 */
export class SonyPSNIdentityProvider extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: SonyPSNApplicationConfiguration })
    @Expose({ name: "applicationConfiguration" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, SonyPSNApplicationConfiguration> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], SonyPSNApplicationConfiguration);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    applicationConfiguration?: Record<string, SonyPSNApplicationConfiguration>;

    @SpeakeasyMetadata()
    @Expose({ name: "buttonText" })
    buttonText?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "client_id" })
    clientId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "client_secret" })
    clientSecret?: string;

    @SpeakeasyMetadata({ elemType: SonyPSNIdentityProviderData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, SonyPSNIdentityProviderData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], SonyPSNIdentityProviderData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, SonyPSNIdentityProviderData>;

    @SpeakeasyMetadata()
    @Expose({ name: "debug" })
    debug?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insertInstant" })
    insertInstant?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "lambdaConfiguration" })
    @Type(() => ProviderLambdaConfiguration)
    lambdaConfiguration?: ProviderLambdaConfiguration;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastUpdateInstant" })
    lastUpdateInstant?: number;

    /**
     * The IdP behavior when no user link has been made yet.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "linkingStrategy" })
    linkingStrategy?: IdentityProviderLinkingStrategy;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;

    @SpeakeasyMetadata({ elemType: IdentityProviderTenantConfiguration })
    @Expose({ name: "tenantConfiguration" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, IdentityProviderTenantConfiguration> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], IdentityProviderTenantConfiguration);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    tenantConfiguration?: Record<string, IdentityProviderTenantConfiguration>;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: IdentityProviderType;
}
