/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SteamAPIMode } from "./steamapimode";
import { Expose } from "class-transformer";

export class SteamApplicationConfiguration extends SpeakeasyBase {
  /**
   * Steam API modes.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "apiMode" })
  apiMode?: SteamAPIMode;

  @SpeakeasyMetadata()
  @Expose({ name: "buttonText" })
  buttonText?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "client_id" })
  clientId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "createRegistration" })
  createRegistration?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  data?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  @Expose({ name: "scope" })
  scope?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "webAPIKey" })
  webAPIKey?: string;
}
