/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TenantWebAuthnWorkflowConfiguration } from "./tenantwebauthnworkflowconfiguration";
import { Expose, Type } from "class-transformer";

/**
 * Tenant-level configuration for WebAuthn
 */
export class TenantWebAuthnConfiguration extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bootstrapWorkflow" })
    @Type(() => TenantWebAuthnWorkflowConfiguration)
    bootstrapWorkflow?: TenantWebAuthnWorkflowConfiguration;

    @SpeakeasyMetadata()
    @Expose({ name: "debug" })
    debug?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "reauthenticationWorkflow" })
    @Type(() => TenantWebAuthnWorkflowConfiguration)
    reauthenticationWorkflow?: TenantWebAuthnWorkflowConfiguration;

    @SpeakeasyMetadata()
    @Expose({ name: "relyingPartyId" })
    relyingPartyId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "relyingPartyName" })
    relyingPartyName?: string;
}
