/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Tenant } from "./tenant";
import { Expose, Type } from "class-transformer";

/**
 * Success
 */
export class TenantResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "tenant" })
    @Type(() => Tenant)
    tenant?: Tenant;

    @SpeakeasyMetadata({ elemType: Tenant })
    @Expose({ name: "tenants" })
    @Type(() => Tenant)
    tenants?: Tenant[];
}
