/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TimeBasedDeletePolicy } from "./timebaseddeletepolicy";
import { Expose, Type } from "class-transformer";

/**
 * A Tenant-level policy for deleting Users.
 */
export class TenantUserDeletePolicy extends SpeakeasyBase {
    /**
     * A policy for deleting Users.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unverified" })
    @Type(() => TimeBasedDeletePolicy)
    unverified?: TimeBasedDeletePolicy;
}
