/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UniqueUsernameConfiguration } from "./uniqueusernameconfiguration";
import { Expose, Type } from "class-transformer";

export class TenantUsernameConfiguration extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "unique" })
  @Type(() => UniqueUsernameConfiguration)
  unique?: UniqueUsernameConfiguration;
}
