/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class TenantRegistrationConfiguration extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "blockedDomains" })
  blockedDomains?: any[];
}
