/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ThemeSearchCriteria } from "./themesearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for Themes.
 */
export class ThemeSearchRequest extends SpeakeasyBase {
    /**
     * Search criteria for themes
     */
    @SpeakeasyMetadata()
    @Expose({ name: "search" })
    @Type(() => ThemeSearchCriteria)
    search?: ThemeSearchCriteria;
}
