/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Theme } from "./theme";
import { Expose, Type } from "class-transformer";

/**
 * Theme API request object.
 */
export class ThemeRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "sourceThemeId" })
    sourceThemeId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "theme" })
    @Type(() => Theme)
    theme?: Theme;
}
