/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The transaction types for Webhooks and other event systems within FusionAuth.
 */
export enum TransactionTypeEnum {
  None = "None",
  Any = "Any",
  SimpleMajority = "SimpleMajority",
  SuperMajority = "SuperMajority",
  AbsoluteMajority = "AbsoluteMajority",
}
