/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TwoFactorTrust } from "./twofactortrust";
import { Expose, Type } from "class-transformer";

export class TwoFactorStatusResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: TwoFactorTrust })
    @Expose({ name: "trusts" })
    @Type(() => TwoFactorTrust)
    trusts?: TwoFactorTrust[];

    @SpeakeasyMetadata()
    @Expose({ name: "twoFactorTrustId" })
    twoFactorTrustId?: string;
}
