/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UserActionReason } from "./useractionreason";
import { Expose, Type } from "class-transformer";

/**
 * User Action Reason API response object.
 */
export class UserActionReasonResponse extends SpeakeasyBase {
    /**
     * Models action reasons.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "userActionReason" })
    @Type(() => UserActionReason)
    userActionReason?: UserActionReason;

    @SpeakeasyMetadata({ elemType: UserActionReason })
    @Expose({ name: "userActionReasons" })
    @Type(() => UserActionReason)
    userActionReasons?: UserActionReason[];
}
