/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Used to express whether the Relying Party requires <a href="https:www.w3.orgTRwebauthn-2#user-verification">user verification<a> for the  current operation.
 */
export enum UserVerificationRequirement {
  Required = "required",
  Preferred = "preferred",
  Discouraged = "discouraged",
}
