/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UserComment } from "./usercomment";
import { Expose, Type } from "class-transformer";

export class UserCommentRequest extends SpeakeasyBase {
  /**
   * A log for an event that happened to a User.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "userComment" })
  @Type(() => UserComment)
  userComment?: UserComment;
}
