/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LogHistory } from "./loghistory";
import { Expose, Type } from "class-transformer";

/**
 * A log for an action that was taken on a User.
 */
export class UserActionLog extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "actioneeUserId" })
  actioneeUserId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "actionerUserId" })
  actionerUserId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "applicationIds" })
  applicationIds?: string[];

  @SpeakeasyMetadata()
  @Expose({ name: "comment" })
  comment?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "emailUserOnEnd" })
  emailUserOnEnd?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "endEventSent" })
  endEventSent?: boolean;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "expiry" })
  expiry?: number;

  /**
   * A historical state of a user log event. Since events can be modified, this stores the historical state.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "history" })
  @Type(() => LogHistory)
  history?: LogHistory;

  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "insertInstant" })
  insertInstant?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "localizedName" })
  localizedName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "localizedOption" })
  localizedOption?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "localizedReason" })
  localizedReason?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "notifyUserOnEnd" })
  notifyUserOnEnd?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "option" })
  option?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "reason" })
  reason?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "reasonCode" })
  reasonCode?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "userActionId" })
  userActionId?: string;
}
