/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UserAction } from "./useraction";
import { Expose, Type } from "class-transformer";

/**
 * User Action API request object.
 */
export class UserActionRequest extends SpeakeasyBase {
  /**
   * An action that can be executed on a user (discipline or reward potentially).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "userAction" })
  @Type(() => UserAction)
  userAction?: UserAction;
}
