/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BreachedPasswordStatus } from "./breachedpasswordstatus";
import { ChangePasswordReason } from "./changepasswordreason";
import { ContentStatus } from "./contentstatus";
import { GroupMember } from "./groupmember";
import { UserRegistration } from "./userregistration";
import { UserTwoFactorConfiguration } from "./usertwofactorconfiguration";
import { Expose, Type } from "class-transformer";

/**
 * The global view of a User. This object contains all global information about the user including birth date, registration information  preferred languages, global attributes, etc.
 */
export class User extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "active" })
  active?: boolean;

  /**
   * A date without a time-zone in the ISO-8601 calendar system, such as 2007-12-03.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "birthDate" })
  birthDate?: string;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "breachedPasswordLastCheckedInstant" })
  breachedPasswordLastCheckedInstant?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "breachedPasswordStatus" })
  breachedPasswordStatus?: BreachedPasswordStatus;

  @SpeakeasyMetadata()
  @Expose({ name: "cleanSpeakId" })
  cleanSpeakId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "connectorId" })
  connectorId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  data?: Record<string, Record<string, any>>;

  @SpeakeasyMetadata()
  @Expose({ name: "email" })
  email?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "encryptionScheme" })
  encryptionScheme?: string;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "expiry" })
  expiry?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "factor" })
  factor?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "firstName" })
  firstName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "fullName" })
  fullName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "imageUrl" })
  imageUrl?: string;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "insertInstant" })
  insertInstant?: number;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "lastLoginInstant" })
  lastLoginInstant?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "lastName" })
  lastName?: string;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "lastUpdateInstant" })
  lastUpdateInstant?: number;

  @SpeakeasyMetadata({ elemType: GroupMember })
  @Expose({ name: "memberships" })
  @Type(() => GroupMember)
  memberships?: GroupMember[];

  @SpeakeasyMetadata()
  @Expose({ name: "middleName" })
  middleName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "mobilePhone" })
  mobilePhone?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "parentEmail" })
  parentEmail?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "password" })
  password?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "passwordChangeReason" })
  passwordChangeReason?: ChangePasswordReason;

  @SpeakeasyMetadata()
  @Expose({ name: "passwordChangeRequired" })
  passwordChangeRequired?: boolean;

  /**
   * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "passwordLastUpdateInstant" })
  passwordLastUpdateInstant?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "preferredLanguages" })
  preferredLanguages?: string[];

  @SpeakeasyMetadata({ elemType: UserRegistration })
  @Expose({ name: "registrations" })
  @Type(() => UserRegistration)
  registrations?: UserRegistration[];

  @SpeakeasyMetadata()
  @Expose({ name: "salt" })
  salt?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "tenantId" })
  tenantId?: string;

  /**
   * Timezone Identifier
   */
  @SpeakeasyMetadata()
  @Expose({ name: "timezone" })
  timezone?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "twoFactor" })
  @Type(() => UserTwoFactorConfiguration)
  twoFactor?: UserTwoFactorConfiguration;

  @SpeakeasyMetadata()
  @Expose({ name: "uniqueUsername" })
  uniqueUsername?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "username" })
  username?: string;

  /**
   * Status for content like usernames, profile attributes, etc.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "usernameStatus" })
  usernameStatus?: ContentStatus;

  @SpeakeasyMetadata()
  @Expose({ name: "verified" })
  verified?: boolean;
}
