/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WebAuthnCredential } from "./webauthncredential";
import { Expose, Type } from "class-transformer";

/**
 * WebAuthn Credential API response
 */
export class WebAuthnCredentialResponse extends SpeakeasyBase {
  /**
   * A User's WebAuthnCredential. Contains all data required to complete WebAuthn authentication ceremonies.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "credential" })
  @Type(() => WebAuthnCredential)
  credential?: WebAuthnCredential;

  @SpeakeasyMetadata({ elemType: WebAuthnCredential })
  @Expose({ name: "credentials" })
  @Type(() => WebAuthnCredential)
  credentials?: WebAuthnCredential[];
}
