/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Identifies the WebAuthn workflow. This will affect the parameters used for credential creation  and request based on the Tenant configuration.
 */
export enum WebAuthnWorkflow {
    Bootstrap = "bootstrap",
    General = "general",
    Reauthentication = "reauthentication",
}
