/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WebAuthnCredential } from "./webauthncredential";
import { Expose, Type } from "class-transformer";

/**
 * API response for completing WebAuthn assertion
 */
export class WebAuthnAssertResponse extends SpeakeasyBase {
    /**
     * A User's WebAuthnCredential. Contains all data required to complete WebAuthn authentication ceremonies.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credential" })
    @Type(() => WebAuthnCredential)
    credential?: WebAuthnCredential;
}
