/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MetaData } from "./metadata";
import { WebAuthnPublicKeyAuthenticationRequest } from "./webauthnpublickeyauthenticationrequest";
import { Expose, Type } from "class-transformer";

/**
 * Request to complete the WebAuthn registration ceremony
 */
export class WebAuthnLoginRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "applicationId" })
    applicationId?: string;

    /**
     * Request to authenticate with WebAuthn
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credential" })
    @Type(() => WebAuthnPublicKeyAuthenticationRequest)
    credential?: WebAuthnPublicKeyAuthenticationRequest;

    @SpeakeasyMetadata()
    @Expose({ name: "ipAddress" })
    ipAddress?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metaData" })
    @Type(() => MetaData)
    metaData?: MetaData;

    @SpeakeasyMetadata()
    @Expose({ name: "newDevice" })
    newDevice?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "noJWT" })
    noJWT?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "origin" })
    origin?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "rpId" })
    rpId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "twoFactorTrustId" })
    twoFactorTrustId?: string;
}
