/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WebAuthnWorkflowEnum } from "./webauthnworkflowenum";
import { Expose } from "class-transformer";

/**
 * API request to start a WebAuthn registration ceremony
 */
export class WebAuthnRegisterStartRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "displayName" })
  displayName?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "userAgent" })
  userAgent?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "userId" })
  userId?: string;

  /**
   * Identifies the WebAuthn workflow. This will affect the parameters used for credential creation  and request based on the Tenant configuration.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "workflow" })
  workflow?: WebAuthnWorkflowEnum;
}
