/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WebhookSearchCriteria } from "./webhooksearchcriteria";
import { Expose, Type } from "class-transformer";

/**
 * Search request for webhooks
 */
export class WebhookSearchRequest extends SpeakeasyBase {
  /**
   * Search criteria for webhooks.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "search" })
  @Type(() => WebhookSearchCriteria)
  search?: WebhookSearchCriteria;
}
