/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { objectToClass, SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { HTTPHeaders } from "./httpheaders";
import { Expose, Transform, Type } from "class-transformer";

export class WebhookData extends SpeakeasyBase {}

/**
 * A server where events are sent. This includes user action events and any other events sent by FusionAuth.
 */
export class Webhook extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connectTimeout" })
    connectTimeout?: number;

    @SpeakeasyMetadata({ elemType: WebhookData })
    @Expose({ name: "data" })
    @Transform(
        ({ value }) => {
            const obj: Record<string, WebhookData> = {};
            for (const key in value) {
                obj[key] = objectToClass(value[key], WebhookData);
            }
            return obj;
        },
        { toClassOnly: true }
    )
    data?: Record<string, WebhookData>;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "eventsEnabled" })
    eventsEnabled?: Record<string, boolean>;

    @SpeakeasyMetadata()
    @Expose({ name: "global" })
    global?: boolean;

    /**
     * Type for webhook headers.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "headers" })
    @Type(() => HTTPHeaders)
    headers?: HTTPHeaders;

    @SpeakeasyMetadata()
    @Expose({ name: "httpAuthenticationPassword" })
    httpAuthenticationPassword?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "httpAuthenticationUsername" })
    httpAuthenticationUsername?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "insertInstant" })
    insertInstant?: number;

    /**
     * The number of milliseconds since the unix epoch: January 1, 1970 00:00:00 UTC. This value is always in UTC.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "lastUpdateInstant" })
    lastUpdateInstant?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "readTimeout" })
    readTimeout?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "sslCertificate" })
    sslCertificate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tenantIds" })
    tenantIds?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url?: string;
}
