/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CancelActionWithIdRequest extends SpeakeasyBase {
    /**
     * The action id of the action to cancel.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=actionId" })
    actionId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    actionRequest?: shared.ActionRequest;
}

export class CancelActionWithIdResponse extends SpeakeasyBase {
    /**
     * Success
     */
    @SpeakeasyMetadata()
    actionResponse?: shared.ActionResponse;

    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
