/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CheckChangePasswordUsingIdWithIdRequest extends SpeakeasyBase {
  /**
   * The change password Id used to find the user. This value is generated by FusionAuth once the change password workflow has been initiated.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=changePasswordId",
  })
  changePasswordId: string;
}

export class CheckChangePasswordUsingIdWithIdResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Error
   */
  @SpeakeasyMetadata()
  errors?: shared.Errors;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
