/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteFormFieldWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the form field to delete.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=fieldId" })
    fieldId: string;
}

export class DeleteFormFieldWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
