/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteUserLinkWithIdRequest extends SpeakeasyBase {
    /**
     * The unique Id of the identity provider.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=identityProviderId" })
    identityProviderId?: string;

    /**
     * The unique Id of the user in the 3rd party identity provider to unlink.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=identityProviderUserId" })
    identityProviderUserId?: string;

    /**
     * The unique Id of the FusionAuth user to unlink.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=userId" })
    userId?: string;
}

export class DeleteUserLinkWithIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    identityProviderLinkResponse?: shared.IdentityProviderLinkResponse;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
