/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteEntityGrantWithIdRequest extends SpeakeasyBase {
  /**
   * The Id of the Entity that the Entity Grant is being deleted for.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=entityId",
  })
  entityId: string;

  /**
   * The unique Id of the tenant used to scope this API request. Only required when there is more than one tenant and the API key is not tenant-scoped.
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=X-FusionAuth-TenantId",
  })
  xFusionAuthTenantId?: string;

  /**
   * The Id of the Entity that the Entity Grant is for.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=recipientEntityId",
  })
  recipientEntityId?: string;

  /**
   * The Id of the User that the Entity Grant is for.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=userId",
  })
  userId?: string;
}

export class DeleteEntityGrantWithIdResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Error
   */
  @SpeakeasyMetadata()
  errors?: shared.Errors;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
