/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteIPAccessControlListWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the IP Access Control List to delete.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=accessControlListId" })
    accessControlListId: string;
}

export class DeleteIPAccessControlListWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
