/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ModifyActionWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the action to modify. This is technically the user action log id.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=actionId" })
    actionId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    actionRequest?: shared.ActionRequest;
}

export class ModifyActionWithIdResponse extends SpeakeasyBase {
    /**
     * Success
     */
    @SpeakeasyMetadata()
    actionResponse?: shared.ActionResponse;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
