/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class PatchEntityTypeWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the Entity Type to update.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=entityTypeId" })
    entityTypeId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    entityTypeRequest?: shared.EntityTypeRequest;
}

export class PatchEntityTypeWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    entityTypeResponse?: shared.EntityTypeResponse;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
