/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class PatchMessengerWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the messenger to update.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=messengerId" })
    messengerId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    messengerRequest?: shared.MessengerRequest;
}

export class PatchMessengerWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    messengerResponse?: shared.MessengerResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
