/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrievePasswordValidationRulesWithTenantIdWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the tenant.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=tenantId" })
    tenantId: string;
}

export class RetrievePasswordValidationRulesWithTenantIdWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    passwordValidationRulesResponse?: shared.PasswordValidationRulesResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
