/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrieveLambdaWithIdRequest extends SpeakeasyBase {
  /**
   * The Id of the lambda.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=lambdaId",
  })
  lambdaId: string;
}

export class RetrieveLambdaWithIdResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Error
   */
  @SpeakeasyMetadata()
  errors?: shared.Errors;

  /**
   * Success
   */
  @SpeakeasyMetadata()
  lambdaResponse?: shared.LambdaResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
