/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrievePendingChildrenWithIdRequest extends SpeakeasyBase {
  /**
   * The email of the parent.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=parentEmail",
  })
  parentEmail?: string;
}

export class RetrievePendingChildrenWithIdResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Error
   */
  @SpeakeasyMetadata()
  errors?: shared.Errors;

  /**
   * Success
   */
  @SpeakeasyMetadata()
  pendingResponse?: shared.PendingResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
