/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrieveThemeWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the theme.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=themeId" })
    themeId: string;
}

export class RetrieveThemeWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    themeResponse?: shared.ThemeResponse;
}
