/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrieveIPAccessControlListWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the IP Access Control List.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=accessControlListId" })
    accessControlListId: string;
}

export class RetrieveIPAccessControlListWithIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    ipAccessControlListResponse?: shared.IPAccessControlListResponse;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
