/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrieveUserConsentWithIdRequest extends SpeakeasyBase {
    /**
     * The User consent Id
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=userConsentId" })
    userConsentId: string;
}

export class RetrieveUserConsentWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    userConsentResponse?: shared.UserConsentResponse;
}
