/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrieveMessageTemplateWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the message template.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=messageTemplateId" })
    messageTemplateId: string;
}

export class RetrieveMessageTemplateWithIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    messageTemplateResponse?: shared.MessageTemplateResponse;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
