/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class SendEmailWithIdRequest extends SpeakeasyBase {
  /**
   * The id for the template.
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=emailTemplateId",
  })
  emailTemplateId: string;

  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  sendRequest?: shared.SendRequest;
}

export class SendEmailWithIdResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Error
   */
  @SpeakeasyMetadata()
  errors?: shared.Errors;

  /**
   * Success
   */
  @SpeakeasyMetadata()
  sendResponse?: shared.SendResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
