/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateFormWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the form to update.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=formId" })
    formId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    formRequest?: shared.FormRequest;
}

export class UpdateFormWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    formResponse?: shared.FormResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
