/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateLambdaWithIdRequest extends SpeakeasyBase {
    /**
     * The Id of the lambda to update.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=lambdaId" })
    lambdaId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    lambdaRequest?: shared.LambdaRequest;
}

export class UpdateLambdaWithIdResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Error
     */
    @SpeakeasyMetadata()
    errors?: shared.Errors;

    /**
     * Success
     */
    @SpeakeasyMetadata()
    lambdaResponse?: shared.LambdaResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
